name: Build DXUI-Installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev qt6-base-dev

    - name: Build DXUI-Installer
      run: |
        qmake Installer.pro
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DXUI-Installer
        path: DXUI-Installer
