name: Build DXUI-Installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev

    - name: Download and install Qt 6.7.1
      run: |
        wget https://download.qt.io/official_releases/qt/6.7/6.7.1/single/qt-everywhere-src-6.7.1.tar.xz
        tar -xf qt-everywhere-src-6.7.1.tar.xz
        cd qt-everywhere-src-6.7.1
        ./configure -prefix $PWD/qtbase
        make -j$(nproc)
        sudo make install
        echo "export PATH=$PWD/qtbase/bin:$PATH" >> $GITHUB_ENV

    - name: Build DXUI-Installer
      run: |
        qmake Installer.pro
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DXUI-Installer
        path: DXUI-Installer
